name: CI-CD

on:
  push:
  pull_request:

jobs:

  install:
    runs-on: self-hosted
    env:
      APP_NAME: TPDevOps
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: echo "App name is $APP_NAME"
      - run: echo "Password is $DB_PASSWORD"   # sera masqué automatiquement

  unit-tests:
    runs-on: self-hosted
    needs: install
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test:unit | tee test-report.txt
      # Upload artefact tests
      - uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test-report.txt
          retention-days: 7

  integration-tests:
    runs-on: self-hosted
    needs: install
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run test:integration

  analyse-artifact:
    runs-on: self-hosted
    needs: unit-tests
    steps:

      # Télécharger artefact du job précédent
      - uses: actions/download-artifact@v4
        with:
          name: test-artifact

      # Utiliser artefact
      - run: |
          echo "Content of artifact:"
          cat test-report.txt

  build-dev:
    runs-on: self-hosted
    needs: [unit-tests, integration-tests]
    env:
      APP_ENV: dev
    steps:
      - uses: actions/checkout@v4
      - run: echo "DEV BUILD" > build.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-dev
          path: build.txt

  build-prod:
    runs-on: self-hosted
    needs: [unit-tests, integration-tests]
    env:
      APP_ENV: prod
    steps:
      - uses: actions/checkout@v4
      - run: echo "PROD BUILD" > build.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-prod
          path: build.txt
